version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: kpo-postgres
    environment:
      POSTGRES_USER: kpo
      POSTGRES_PASSWORD: kpo
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: kpo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kpo-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: unless-stopped

  kafka-init:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kpo-kafka-init
    depends_on:
      - kafka
    entrypoint: ["/bin/bash", "-lc"]
    command: >
      "
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic payments.request --partitions 1 --replication-factor 1 &&
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic payments.result  --partitions 1 --replication-factor 1
      "
    restart: "no"

  payments:
    build: ./payments
    container_name: kpo-payments
    environment:
      DATABASE_URL: postgres://kpo:kpo@postgres:5432/app?sslmode=disable
      KAFKA_BROKERS: kafka:29092
    depends_on:
      - postgres
      - kafka
    ports:
      - "8082:8080"
    restart: unless-stopped

  orders:
    build: ./orders
    container_name: kpo-orders
    environment:
      DATABASE_URL: postgres://kpo:kpo@postgres:5432/app?sslmode=disable
      KAFKA_BROKERS: kafka:29092
      PAYMENTS_URL: http://payments:8080
    depends_on:
      - postgres
      - kafka
      - payments
    ports:
      - "8081:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: kpo-frontend
    environment:
      ORDERS_URL: http://orders:8080
      PAYMENTS_URL: http://payments:8080
    depends_on:
      - orders
      - payments
    ports:
      - "8080:8080"
    restart: unless-stopped

